apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powerstore-nfs
provisioner: csi-powerstore.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  arrayID: "Unique"
  FsType: nfs
  nasName: nas-server # (Optional) If not specified, value from config.yaml will be used
  allowRoot: "false"  # enables or disables root squashing
